<?php
/**
 * ArtifactDependencyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TeamCityClient;

/**
 * ArtifactDependencyTest Class Doc Comment
 *
 * @category    Class
 * @description ArtifactDependency
 * @package     TeamCityClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ArtifactDependencyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ArtifactDependency"
     */
    public function testArtifactDependency()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "disabled"
     */
    public function testPropertyDisabled()
    {
    }

    /**
     * Test attribute "inherited"
     */
    public function testPropertyInherited()
    {
    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
    }

    /**
     * Test attribute "source_build_type"
     */
    public function testPropertySourceBuildType()
    {
    }
}
