<?php
/**
 * BuildTriggeringOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TeamCityClient;

/**
 * BuildTriggeringOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description BuildTriggeringOptions
 * @package     TeamCityClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BuildTriggeringOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BuildTriggeringOptions"
     */
    public function testBuildTriggeringOptions()
    {
    }

    /**
     * Test attribute "clean_sources"
     */
    public function testPropertyCleanSources()
    {
    }

    /**
     * Test attribute "clean_sources_in_all_dependencies"
     */
    public function testPropertyCleanSourcesInAllDependencies()
    {
    }

    /**
     * Test attribute "rebuild_all_dependencies"
     */
    public function testPropertyRebuildAllDependencies()
    {
    }

    /**
     * Test attribute "rebuild_failed_or_incomplete_dependencies"
     */
    public function testPropertyRebuildFailedOrIncompleteDependencies()
    {
    }

    /**
     * Test attribute "queue_at_top"
     */
    public function testPropertyQueueAtTop()
    {
    }

    /**
     * Test attribute "freeze_settings"
     */
    public function testPropertyFreezeSettings()
    {
    }

    /**
     * Test attribute "tag_dependencies"
     */
    public function testPropertyTagDependencies()
    {
    }

    /**
     * Test attribute "rebuild_dependencies"
     */
    public function testPropertyRebuildDependencies()
    {
    }
}
