<?php
/**
 * FileChangeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TeamCityClient;

/**
 * FileChangeTest Class Doc Comment
 *
 * @category    Class
 * @description FileChange
 * @package     TeamCityClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileChangeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FileChange"
     */
    public function testFileChange()
    {
    }

    /**
     * Test attribute "before_revision"
     */
    public function testPropertyBeforeRevision()
    {
    }

    /**
     * Test attribute "after_revision"
     */
    public function testPropertyAfterRevision()
    {
    }

    /**
     * Test attribute "change_type"
     */
    public function testPropertyChangeType()
    {
    }

    /**
     * Test attribute "change_type_comment"
     */
    public function testPropertyChangeTypeComment()
    {
    }

    /**
     * Test attribute "file"
     */
    public function testPropertyFile()
    {
    }

    /**
     * Test attribute "relative_file"
     */
    public function testPropertyRelativeFile()
    {
    }

    /**
     * Test attribute "directory"
     */
    public function testPropertyDirectory()
    {
    }
}
