<?php
/**
 * HealthItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TeamCityClient;

/**
 * HealthItemTest Class Doc Comment
 *
 * @category    Class
 * @description HealthItem
 * @package     TeamCityClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HealthItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HealthItem"
     */
    public function testHealthItem()
    {
    }

    /**
     * Test attribute "identity"
     */
    public function testPropertyIdentity()
    {
    }

    /**
     * Test attribute "severity"
     */
    public function testPropertySeverity()
    {
    }

    /**
     * Test attribute "health_category"
     */
    public function testPropertyHealthCategory()
    {
    }
}
