<?php
/**
 * ProjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace TeamCityClient;

/**
 * ProjectTest Class Doc Comment
 *
 * @category    Class
 * @description Project
 * @package     TeamCityClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Project"
     */
    public function testProject()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "internal_id"
     */
    public function testPropertyInternalId()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "parent_project_id"
     */
    public function testPropertyParentProjectId()
    {
    }

    /**
     * Test attribute "parent_project_internal_id"
     */
    public function testPropertyParentProjectInternalId()
    {
    }

    /**
     * Test attribute "parent_project_name"
     */
    public function testPropertyParentProjectName()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "href"
     */
    public function testPropertyHref()
    {
    }

    /**
     * Test attribute "web_url"
     */
    public function testPropertyWebUrl()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "parent_project"
     */
    public function testPropertyParentProject()
    {
    }

    /**
     * Test attribute "read_only_ui"
     */
    public function testPropertyReadOnlyUi()
    {
    }

    /**
     * Test attribute "default_template"
     */
    public function testPropertyDefaultTemplate()
    {
    }

    /**
     * Test attribute "build_types"
     */
    public function testPropertyBuildTypes()
    {
    }

    /**
     * Test attribute "templates"
     */
    public function testPropertyTemplates()
    {
    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {
    }

    /**
     * Test attribute "vcs_roots"
     */
    public function testPropertyVcsRoots()
    {
    }

    /**
     * Test attribute "project_features"
     */
    public function testPropertyProjectFeatures()
    {
    }

    /**
     * Test attribute "projects"
     */
    public function testPropertyProjects()
    {
    }

    /**
     * Test attribute "cloud_profiles"
     */
    public function testPropertyCloudProfiles()
    {
    }

    /**
     * Test attribute "locator"
     */
    public function testPropertyLocator()
    {
    }
}
