<?php
/**
 * BuildApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TeamCityClient;

use \TeamCityClient\Configuration;
use \TeamCityClient\ApiException;
use \TeamCityClient\ObjectSerializer;

/**
 * BuildApiTest Class Doc Comment
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuildApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addLogMessage
     *
     * Adds a message to the build log. Service messages are accepted..
     *
     */
    public function testAddLogMessage()
    {
    }

    /**
     * Test case for addProblem
     *
     * .
     *
     */
    public function testAddProblem()
    {
    }

    /**
     * Test case for addTags
     *
     * .
     *
     */
    public function testAddTags()
    {
    }

    /**
     * Test case for addTagsMultiple
     *
     * .
     *
     */
    public function testAddTagsMultiple()
    {
    }

    /**
     * Test case for cancelBuild
     *
     * .
     *
     */
    public function testCancelBuild()
    {
    }

    /**
     * Test case for cancelBuild_0
     *
     * .
     *
     */
    public function testCancelBuild0()
    {
    }

    /**
     * Test case for cancelMultiple
     *
     * .
     *
     */
    public function testCancelMultiple()
    {
    }

    /**
     * Test case for deleteAllParameters
     *
     * .
     *
     */
    public function testDeleteAllParameters()
    {
    }

    /**
     * Test case for deleteBuild
     *
     * .
     *
     */
    public function testDeleteBuild()
    {
    }

    /**
     * Test case for deleteBuilds
     *
     * .
     *
     */
    public function testDeleteBuilds()
    {
    }

    /**
     * Test case for deleteComment
     *
     * .
     *
     */
    public function testDeleteComment()
    {
    }

    /**
     * Test case for deleteCommentMultiple
     *
     * .
     *
     */
    public function testDeleteCommentMultiple()
    {
    }

    /**
     * Test case for deleteMultiple
     *
     * .
     *
     */
    public function testDeleteMultiple()
    {
    }

    /**
     * Test case for deleteParameter
     *
     * .
     *
     */
    public function testDeleteParameter()
    {
    }

    /**
     * Test case for getArtifactDependencyChanges
     *
     * .
     *
     */
    public function testGetArtifactDependencyChanges()
    {
    }

    /**
     * Test case for getArtifactsDirectory
     *
     * .
     *
     */
    public function testGetArtifactsDirectory()
    {
    }

    /**
     * Test case for getBuildFinishDate
     *
     * .
     *
     */
    public function testGetBuildFinishDate()
    {
    }

    /**
     * Test case for getBuildNumber
     *
     * .
     *
     */
    public function testGetBuildNumber()
    {
    }

    /**
     * Test case for getBuildStatusText
     *
     * .
     *
     */
    public function testGetBuildStatusText()
    {
    }

    /**
     * Test case for getCanceledInfo
     *
     * .
     *
     */
    public function testGetCanceledInfo()
    {
    }

    /**
     * Test case for getChildren
     *
     * .
     *
     */
    public function testGetChildren()
    {
    }

    /**
     * Test case for getChildrenAlias
     *
     * .
     *
     */
    public function testGetChildrenAlias()
    {
    }

    /**
     * Test case for getContent
     *
     * .
     *
     */
    public function testGetContent()
    {
    }

    /**
     * Test case for getContentAlias
     *
     * .
     *
     */
    public function testGetContentAlias()
    {
    }

    /**
     * Test case for getMetadata
     *
     * .
     *
     */
    public function testGetMetadata()
    {
    }

    /**
     * Test case for getMultiple
     *
     * .
     *
     */
    public function testGetMultiple()
    {
    }

    /**
     * Test case for getParameter
     *
     * .
     *
     */
    public function testGetParameter()
    {
    }

    /**
     * Test case for getParameterValueLong
     *
     * .
     *
     */
    public function testGetParameterValueLong()
    {
    }

    /**
     * Test case for getParameter_0
     *
     * .
     *
     */
    public function testGetParameter0()
    {
    }

    /**
     * Test case for getParameters
     *
     * .
     *
     */
    public function testGetParameters()
    {
    }

    /**
     * Test case for getPinData
     *
     * .
     *
     */
    public function testGetPinData()
    {
    }

    /**
     * Test case for getPinned
     *
     * .
     *
     */
    public function testGetPinned()
    {
    }

    /**
     * Test case for getProblems
     *
     * .
     *
     */
    public function testGetProblems()
    {
    }

    /**
     * Test case for getResolvedParameter
     *
     * .
     *
     */
    public function testGetResolvedParameter()
    {
    }

    /**
     * Test case for getRoot
     *
     * .
     *
     */
    public function testGetRoot()
    {
    }

    /**
     * Test case for getTests
     *
     * .
     *
     */
    public function testGetTests()
    {
    }

    /**
     * Test case for getZipped
     *
     * .
     *
     */
    public function testGetZipped()
    {
    }

    /**
     * Test case for markBuildAsRunning
     *
     * Starts the queued build as an agent-less build and returns the corresponding running build..
     *
     */
    public function testMarkBuildAsRunning()
    {
    }

    /**
     * Test case for pinBuild
     *
     * .
     *
     */
    public function testPinBuild()
    {
    }

    /**
     * Test case for pinMultiple
     *
     * .
     *
     */
    public function testPinMultiple()
    {
    }

    /**
     * Test case for removeTagsMultiple
     *
     * .
     *
     */
    public function testRemoveTagsMultiple()
    {
    }

    /**
     * Test case for replaceComment
     *
     * .
     *
     */
    public function testReplaceComment()
    {
    }

    /**
     * Test case for replaceCommentMultiple
     *
     * .
     *
     */
    public function testReplaceCommentMultiple()
    {
    }

    /**
     * Test case for replaceTags
     *
     * .
     *
     */
    public function testReplaceTags()
    {
    }

    /**
     * Test case for resetBuildFinishParameters
     *
     * .
     *
     */
    public function testResetBuildFinishParameters()
    {
    }

    /**
     * Test case for serveAggregatedBuildStatus
     *
     * .
     *
     */
    public function testServeAggregatedBuildStatus()
    {
    }

    /**
     * Test case for serveAggregatedBuildStatusIcon
     *
     * .
     *
     */
    public function testServeAggregatedBuildStatusIcon()
    {
    }

    /**
     * Test case for serveAllBuilds
     *
     * .
     *
     */
    public function testServeAllBuilds()
    {
    }

    /**
     * Test case for serveBuild
     *
     * .
     *
     */
    public function testServeBuild()
    {
    }

    /**
     * Test case for serveBuildActualParameters
     *
     * .
     *
     */
    public function testServeBuildActualParameters()
    {
    }

    /**
     * Test case for serveBuildFieldByBuildOnly
     *
     * .
     *
     */
    public function testServeBuildFieldByBuildOnly()
    {
    }

    /**
     * Test case for serveBuildRelatedIssues
     *
     * .
     *
     */
    public function testServeBuildRelatedIssues()
    {
    }

    /**
     * Test case for serveBuildRelatedIssuesOld
     *
     * .
     *
     */
    public function testServeBuildRelatedIssuesOld()
    {
    }

    /**
     * Test case for serveBuildStatisticValue
     *
     * .
     *
     */
    public function testServeBuildStatisticValue()
    {
    }

    /**
     * Test case for serveBuildStatisticValues
     *
     * .
     *
     */
    public function testServeBuildStatisticValues()
    {
    }

    /**
     * Test case for serveBuildStatusIcon
     *
     * .
     *
     */
    public function testServeBuildStatusIcon()
    {
    }

    /**
     * Test case for serveSourceFile
     *
     * .
     *
     */
    public function testServeSourceFile()
    {
    }

    /**
     * Test case for serveTags
     *
     * .
     *
     */
    public function testServeTags()
    {
    }

    /**
     * Test case for setBuildNumber
     *
     * .
     *
     */
    public function testSetBuildNumber()
    {
    }

    /**
     * Test case for setBuildPinData
     *
     * .
     *
     */
    public function testSetBuildPinData()
    {
    }

    /**
     * Test case for setBuildStatusText
     *
     * .
     *
     */
    public function testSetBuildStatusText()
    {
    }

    /**
     * Test case for setFinishedTime
     *
     * Marks the running build as finished by passing agent time of the build finish. An empty finish date means \"now\"..
     *
     */
    public function testSetFinishedTime()
    {
    }

    /**
     * Test case for setParameter
     *
     * .
     *
     */
    public function testSetParameter()
    {
    }

    /**
     * Test case for setParameterValueLong
     *
     * .
     *
     */
    public function testSetParameterValueLong()
    {
    }

    /**
     * Test case for setParameter_0
     *
     * .
     *
     */
    public function testSetParameter0()
    {
    }

    /**
     * Test case for setParameters
     *
     * .
     *
     */
    public function testSetParameters()
    {
    }

    /**
     * Test case for unpinBuild
     *
     * .
     *
     */
    public function testUnpinBuild()
    {
    }
}
