<?php
/**
 * BuildQueueApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TeamCityClient;

use \TeamCityClient\Configuration;
use \TeamCityClient\ApiException;
use \TeamCityClient\ObjectSerializer;

/**
 * BuildQueueApiTest Class Doc Comment
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuildQueueApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addTags
     *
     * .
     *
     */
    public function testAddTags()
    {
    }

    /**
     * Test case for cancelBuild
     *
     * .
     *
     */
    public function testCancelBuild()
    {
    }

    /**
     * Test case for cancelBuild_0
     *
     * .
     *
     */
    public function testCancelBuild0()
    {
    }

    /**
     * Test case for deleteBuild
     *
     * .
     *
     */
    public function testDeleteBuild()
    {
    }

    /**
     * Test case for deleteBuildsExperimental
     *
     * .
     *
     */
    public function testDeleteBuildsExperimental()
    {
    }

    /**
     * Test case for getBuild
     *
     * .
     *
     */
    public function testGetBuild()
    {
    }

    /**
     * Test case for getBuilds
     *
     * .
     *
     */
    public function testGetBuilds()
    {
    }

    /**
     * Test case for queueNewBuild
     *
     * .
     *
     */
    public function testQueueNewBuild()
    {
    }

    /**
     * Test case for replaceBuilds
     *
     * .
     *
     */
    public function testReplaceBuilds()
    {
    }

    /**
     * Test case for replaceTags
     *
     * .
     *
     */
    public function testReplaceTags()
    {
    }

    /**
     * Test case for serveBuildFieldByBuildOnly
     *
     * .
     *
     */
    public function testServeBuildFieldByBuildOnly()
    {
    }

    /**
     * Test case for serveCompatibleAgents
     *
     * .
     *
     */
    public function testServeCompatibleAgents()
    {
    }

    /**
     * Test case for serveTags
     *
     * .
     *
     */
    public function testServeTags()
    {
    }

    /**
     * Test case for setBuildQueueOrder
     *
     * .
     *
     */
    public function testSetBuildQueueOrder()
    {
    }

    /**
     * Test case for setBuildQueuePosition
     *
     * .
     *
     */
    public function testSetBuildQueuePosition()
    {
    }

    /**
     * Test case for setBuildQueuePosition_0
     *
     * .
     *
     */
    public function testSetBuildQueuePosition0()
    {
    }
}
