<?php
/**
 * CloudInstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TeamCityClient;

use \TeamCityClient\Configuration;
use \TeamCityClient\ApiException;
use \TeamCityClient\ObjectSerializer;

/**
 * CloudInstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CloudInstanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for serveImage
     *
     * .
     *
     */
    public function testServeImage()
    {
    }

    /**
     * Test case for serveImages
     *
     * .
     *
     */
    public function testServeImages()
    {
    }

    /**
     * Test case for serveInstance
     *
     * .
     *
     */
    public function testServeInstance()
    {
    }

    /**
     * Test case for serveInstances
     *
     * .
     *
     */
    public function testServeInstances()
    {
    }

    /**
     * Test case for serveProfile
     *
     * .
     *
     */
    public function testServeProfile()
    {
    }

    /**
     * Test case for serveProfiles
     *
     * .
     *
     */
    public function testServeProfiles()
    {
    }

    /**
     * Test case for startInstance
     *
     * .
     *
     */
    public function testStartInstance()
    {
    }

    /**
     * Test case for stopInstance
     *
     * .
     *
     */
    public function testStopInstance()
    {
    }
}
