<?php
/**
 * DebugApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TeamCityClient;

use \TeamCityClient\Configuration;
use \TeamCityClient\ApiException;
use \TeamCityClient\ObjectSerializer;

/**
 * DebugApiTest Class Doc Comment
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DebugApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteCurrentRememberMe
     *
     * .
     *
     */
    public function testDeleteCurrentRememberMe()
    {
    }

    /**
     * Test case for emptyTask
     *
     * .
     *
     */
    public function testEmptyTask()
    {
    }

    /**
     * Test case for executeDBQuery
     *
     * .
     *
     */
    public function testExecuteDBQuery()
    {
    }

    /**
     * Test case for getBuildChainOptimizationLog
     *
     * .
     *
     */
    public function testGetBuildChainOptimizationLog()
    {
    }

    /**
     * Test case for getCachedBuildPromotions
     *
     * .
     *
     */
    public function testGetCachedBuildPromotions()
    {
    }

    /**
     * Test case for getCachedBuildPromotionsStats
     *
     * .
     *
     */
    public function testGetCachedBuildPromotionsStats()
    {
    }

    /**
     * Test case for getCachedBuildsStat
     *
     * .
     *
     */
    public function testGetCachedBuildsStat()
    {
    }

    /**
     * Test case for getCurrentSession
     *
     * .
     *
     */
    public function testGetCurrentSession()
    {
    }

    /**
     * Test case for getCurrentSessionMaxInactiveInterval
     *
     * .
     *
     */
    public function testGetCurrentSessionMaxInactiveInterval()
    {
    }

    /**
     * Test case for getCurrentUserPermissions
     *
     * .
     *
     */
    public function testGetCurrentUserPermissions()
    {
    }

    /**
     * Test case for getDate
     *
     * .
     *
     */
    public function testGetDate()
    {
    }

    /**
     * Test case for getDiagnosticsPerfStats
     *
     * .
     *
     */
    public function testGetDiagnosticsPerfStats()
    {
    }

    /**
     * Test case for getEnvironmentVariables
     *
     * .
     *
     */
    public function testGetEnvironmentVariables()
    {
    }

    /**
     * Test case for getHashed
     *
     * .
     *
     */
    public function testGetHashed()
    {
    }

    /**
     * Test case for getIpAddress
     *
     * .
     *
     */
    public function testGetIpAddress()
    {
    }

    /**
     * Test case for getRawInvestigations
     *
     * .
     *
     */
    public function testGetRawInvestigations()
    {
    }

    /**
     * Test case for getRequestDetails
     *
     * .
     *
     */
    public function testGetRequestDetails()
    {
    }

    /**
     * Test case for getScrambled
     *
     * .
     *
     */
    public function testGetScrambled()
    {
    }

    /**
     * Test case for getSessions
     *
     * .
     *
     */
    public function testGetSessions()
    {
    }

    /**
     * Test case for getSystemProperties
     *
     * .
     *
     */
    public function testGetSystemProperties()
    {
    }

    /**
     * Test case for getThreadDump
     *
     * .
     *
     */
    public function testGetThreadDump()
    {
    }

    /**
     * Test case for getThreadInterrupted
     *
     * .
     *
     */
    public function testGetThreadInterrupted()
    {
    }

    /**
     * Test case for getUnscrambled
     *
     * .
     *
     */
    public function testGetUnscrambled()
    {
    }

    /**
     * Test case for interruptThread
     *
     * .
     *
     */
    public function testInterruptThread()
    {
    }

    /**
     * Test case for invalidateCurrentSession
     *
     * .
     *
     */
    public function testInvalidateCurrentSession()
    {
    }

    /**
     * Test case for listDBTables
     *
     * .
     *
     */
    public function testListDBTables()
    {
    }

    /**
     * Test case for newRememberMe
     *
     * .
     *
     */
    public function testNewRememberMe()
    {
    }

    /**
     * Test case for postRequestDetails
     *
     * .
     *
     */
    public function testPostRequestDetails()
    {
    }

    /**
     * Test case for putRequestDetails
     *
     * .
     *
     */
    public function testPutRequestDetails()
    {
    }

    /**
     * Test case for requestFinalization
     *
     * .
     *
     */
    public function testRequestFinalization()
    {
    }

    /**
     * Test case for requestGc
     *
     * .
     *
     */
    public function testRequestGc()
    {
    }

    /**
     * Test case for resetCacheProjectMutes
     *
     * .
     *
     */
    public function testResetCacheProjectMutes()
    {
    }

    /**
     * Test case for runProcess
     *
     * .
     *
     */
    public function testRunProcess()
    {
    }

    /**
     * Test case for saveMemoryDump
     *
     * .
     *
     */
    public function testSaveMemoryDump()
    {
    }

    /**
     * Test case for scheduleCheckingForChanges
     *
     * .
     *
     */
    public function testScheduleCheckingForChanges()
    {
    }

    /**
     * Test case for setCurrentSessionMaxInactiveInterval
     *
     * .
     *
     */
    public function testSetCurrentSessionMaxInactiveInterval()
    {
    }
}
