<?php
/**
 * VcsRootApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TeamCityClient;

use \TeamCityClient\Configuration;
use \TeamCityClient\ApiException;
use \TeamCityClient\ObjectSerializer;

/**
 * VcsRootApiTest Class Doc Comment
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VcsRootApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addRoot
     *
     * .
     *
     */
    public function testAddRoot()
    {
    }

    /**
     * Test case for changeProperties
     *
     * .
     *
     */
    public function testChangeProperties()
    {
    }

    /**
     * Test case for deleteAllProperties
     *
     * .
     *
     */
    public function testDeleteAllProperties()
    {
    }

    /**
     * Test case for deleteParameter
     *
     * .
     *
     */
    public function testDeleteParameter()
    {
    }

    /**
     * Test case for deleteRoot
     *
     * .
     *
     */
    public function testDeleteRoot()
    {
    }

    /**
     * Test case for getSettingsFile
     *
     * .
     *
     */
    public function testGetSettingsFile()
    {
    }

    /**
     * Test case for putParameter
     *
     * .
     *
     */
    public function testPutParameter()
    {
    }

    /**
     * Test case for serveField
     *
     * .
     *
     */
    public function testServeField()
    {
    }

    /**
     * Test case for serveInstanceField
     *
     * .
     *
     */
    public function testServeInstanceField()
    {
    }

    /**
     * Test case for serveProperties
     *
     * .
     *
     */
    public function testServeProperties()
    {
    }

    /**
     * Test case for serveProperty
     *
     * .
     *
     */
    public function testServeProperty()
    {
    }

    /**
     * Test case for serveRoot
     *
     * .
     *
     */
    public function testServeRoot()
    {
    }

    /**
     * Test case for serveRootInstance
     *
     * .
     *
     */
    public function testServeRootInstance()
    {
    }

    /**
     * Test case for serveRootInstanceProperties
     *
     * .
     *
     */
    public function testServeRootInstanceProperties()
    {
    }

    /**
     * Test case for serveRootInstances
     *
     * .
     *
     */
    public function testServeRootInstances()
    {
    }

    /**
     * Test case for serveRoots
     *
     * .
     *
     */
    public function testServeRoots()
    {
    }

    /**
     * Test case for setField
     *
     * .
     *
     */
    public function testSetField()
    {
    }

    /**
     * Test case for setInstanceField
     *
     * .
     *
     */
    public function testSetInstanceField()
    {
    }
}
