<?php
/**
 * VcsRootInstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TeamCity REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.15
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace TeamCityClient;

use \TeamCityClient\Configuration;
use \TeamCityClient\ApiException;
use \TeamCityClient\ObjectSerializer;

/**
 * VcsRootInstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  TeamCityClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VcsRootInstanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteInstanceField
     *
     * .
     *
     */
    public function testDeleteInstanceField()
    {
    }

    /**
     * Test case for deleteRepositoryState
     *
     * .
     *
     */
    public function testDeleteRepositoryState()
    {
    }

    /**
     * Test case for getChildren
     *
     * .
     *
     */
    public function testGetChildren()
    {
    }

    /**
     * Test case for getChildrenAlias
     *
     * .
     *
     */
    public function testGetChildrenAlias()
    {
    }

    /**
     * Test case for getContent
     *
     * .
     *
     */
    public function testGetContent()
    {
    }

    /**
     * Test case for getContentAlias
     *
     * .
     *
     */
    public function testGetContentAlias()
    {
    }

    /**
     * Test case for getMetadata
     *
     * .
     *
     */
    public function testGetMetadata()
    {
    }

    /**
     * Test case for getRepositoryState
     *
     * .
     *
     */
    public function testGetRepositoryState()
    {
    }

    /**
     * Test case for getRepositoryStateCreationDate
     *
     * .
     *
     */
    public function testGetRepositoryStateCreationDate()
    {
    }

    /**
     * Test case for getRoot
     *
     * .
     *
     */
    public function testGetRoot()
    {
    }

    /**
     * Test case for getZipped
     *
     * .
     *
     */
    public function testGetZipped()
    {
    }

    /**
     * Test case for scheduleCheckingForChanges
     *
     * .
     *
     */
    public function testScheduleCheckingForChanges()
    {
    }

    /**
     * Test case for scheduleCheckingForChanges_0
     *
     * .
     *
     */
    public function testScheduleCheckingForChanges0()
    {
    }

    /**
     * Test case for serveInstance
     *
     * .
     *
     */
    public function testServeInstance()
    {
    }

    /**
     * Test case for serveInstanceField
     *
     * .
     *
     */
    public function testServeInstanceField()
    {
    }

    /**
     * Test case for serveInstances
     *
     * .
     *
     */
    public function testServeInstances()
    {
    }

    /**
     * Test case for serveRootInstanceProperties
     *
     * .
     *
     */
    public function testServeRootInstanceProperties()
    {
    }

    /**
     * Test case for setInstanceField
     *
     * .
     *
     */
    public function testSetInstanceField()
    {
    }

    /**
     * Test case for setRepositoryState
     *
     * .
     *
     */
    public function testSetRepositoryState()
    {
    }
}
